version = 1

[[items]]
type = "leaf"
ca = "infra"
common_name = "rabbitmq"
usage = "serverAuth"
san = "DNS:localhost,DNS:rabbitmq,DNS:stage-rabbitmq,DNS:dev-rabbitmq,DNS:host.docker.internal,IP:127.0.0.1"
cert_path = "certs/issued/rabbitmq/rabbitmq-server.pem"
key_path = "certs/issued/rabbitmq/rabbitmq-server.key"
bundle_path = "certs/issued/rabbitmq/trust-bundle.pem"

[[items]]
type = "leaf"
ca = "infra"
common_name = "rabbitmq-auth-http-client"
usage = "clientAuth"
cert_path = "certs/issued/rabbitmq/rabbitmq-client.pem"
key_path = "certs/issued/rabbitmq/rabbitmq-client.key"
bundle_path = "certs/issued/rabbitmq/trust-bundle.pem"
