# ===== TLS listeners =====
listeners.ssl.default = 5671
listeners.tcp = none

ssl_options.cacertfile = /certs/trust-bundle.pem
ssl_options.certfile = /certs/rabbitmq-server.pem
ssl_options.keyfile = /certs/rabbitmq-server.key
ssl_options.verify = verify_peer
ssl_options.fail_if_no_peer_cert = true
ssl_options.versions.1 = tlsv1.3
ssl_options.depth = 1
ssl_options.ciphers.1 = TLS_AES_256_GCM_SHA384
ssl_options.ciphers.2 = TLS_CHACHA20_POLY1305_SHA256
ssl_options.ciphers.3 = TLS_AES_128_GCM_SHA256

# ===== Management API =====
management.tcp.port = 15672

# ===== Authentication =====
auth_mechanisms.1 = EXTERNAL
auth_mechanisms.2 = PLAIN
ssl_cert_login_from = common_name

# ===== Authorization backends =====
auth_backends.1 = internal
auth_backends.2 = cache

auth_cache.cached_backend = http
auth_cache.cache_ttl = 15000

auth_http.user_path = https://host.docker.internal:9008/auth/user
auth_http.vhost_path = https://host.docker.internal:9008/auth/vhost
auth_http.resource_path = https://host.docker.internal:9008/auth/resource
auth_http.topic_path = https://host.docker.internal:9008/auth/topic
auth_http.http_method = post
auth_http.ssl_options.cacertfile = /certs/trust-bundle.pem
auth_http.ssl_options.certfile = /certs/rabbitmq-client.pem
auth_http.ssl_options.keyfile = /certs/rabbitmq-client.key
auth_http.ssl_options.verify = verify_peer