limit_conn_zone $binary_remote_addr zone=shared_conn_limit:10m;
limit_req_zone $binary_remote_addr zone=shared_req_limit:10m rate=30r/s;

server {
    listen 80;
    server_name _;

    server_tokens off;
    client_max_body_size 10M;

    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    limit_conn shared_conn_limit 50;
    limit_req zone=shared_req_limit burst=60 nodelay;

    include /etc/nginx/conf.d/apps/*.conf;

    location / {
        return 404;
    }
}
