"""add cascade delete to skills

Revision ID: 7a28c73afbe8
Revises: 23d023fbe347
Create Date: 2025-12-01 15:31:32.366449

"""

from __future__ import annotations

from typing import TYPE_CHECKING

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "7a28c73afbe8"
down_revision: str | Sequence[str] | None = "23d023fbe347"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "skills_aic_fkey",  # 外键名称
        "skills",
        type_="foreignkey",
    )

    op.create_foreign_key(
        "skills_aic_fkey",
        "skills",
        "agents",
        ["aic"],
        ["aic"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("skills_aic_fkey", "skills", type_="foreignkey")

    op.create_foreign_key(
        "skills_aic_fkey",
        "skills",
        "agents",
        ["aic"],
        ["aic"],
        ondelete=None,
    )
    # ### end Alembic commands ###
