"""add skills indices

Revision ID: 865c8015dad7
Revises: 9c203efe545f
Create Date: 2025-12-24 10:56:39.358312

"""

from __future__ import annotations

from typing import TYPE_CHECKING

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "865c8015dad7"
down_revision: str | Sequence[str] | None = "9c203efe545f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_skills_aic", "skills", ["aic"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_skills_aic", table_name="skills")
    # ### end Alembic commands ###
