"""add skills table

Revision ID: be170784a108
Revises: d5215c4a631e
Create Date: 2025-11-24 16:44:44.307713

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "be170784a108"
down_revision: str | Sequence[str] | None = "d5215c4a631e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skills",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("aic", sa.String(length=255), nullable=False),
        sa.Column("skill_id", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("embedding", Vector(1024), nullable=True),
        sa.ForeignKeyConstraint(
            ["aic"],
            ["agents.aic"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skills")
    # ### end Alembic commands ###
