"""add agent aic filed

Revision ID: c26a582dbc62
Revises: 485fedef7564
Create Date: 2025-04-30 11:09:05.862271

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c26a582dbc62"
down_revision: str | None = "485fedef7564"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent", sa.Column("aic", sa.String(32), nullable=True))
    op.create_index(op.f("ix_agent_aic"), "agent", ["aic"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_aic"), table_name="agent")
    op.drop_column("agent", "aic")
    # ### end Alembic commands ###
