#!/bin/bash
# setup-handshake-axuan.sh — 为阿轩生成 A2A 握手密钥对（AID + 私钥）
# 创建: 2026-09-14 07:27 (Asia/Shanghai) · 墨白指示走 A 方案
# ⚠️ 已被取代: 2026-09-14 0452068 commit 引入官方 scripts/setup-handshake.sh（通用·slug 约定路径）。
#   本脚本是早期精简版（缺 endpoint/expires_at/capabilities 字段）。下次生成 AID 请用官方版:
#     bash scripts/setup-handshake.sh <slug> <host> [port] [name]
#   本脚本保留作为历史记录 / 仅作应急 fallback，不要在新生成场景里使用。
# 参考: 若兰 07:26 转发的精确口径
#   - AID 是自签的（generateKeyPairSync），私钥只能本机生成
#   - csb-security/data/axuan-aid.json + csb-security/data/axuan-private-key.pem
#   - start-v5.sh 会从 slug 推导路径
# 注: 跟若兰侧 setup-handshake-axuan.sh 路径/文件名约定一致
#     （若兰侧输出 config/security/，本机输出 csb-security/data/，这是与 start-v5.sh 对齐的版本）
set -e

cd /home/node/.openclaw/workspace
mkdir -p csb-security/data

AID_PATH="csb-security/data/axuan-aid.json"
KEY_PATH="csb-security/data/axuan-private-key.pem"

# 备份已存在的（如果有）
if [ -f "$AID_PATH" ]; then
    echo "[1/5] 备份已存在的 $AID_PATH → ${AID_PATH}.bak.$(date +%Y%m%d-%H%M%S)"
    cp "$AID_PATH" "${AID_PATH}.bak.$(date +%Y%m%d-%H%M%S)"
fi
if [ -f "$KEY_PATH" ]; then
    echo "[1/5] 备份已存在的 $KEY_PATH → ${KEY_PATH}.bak.$(date +%Y%m%d-%H%M%S)"
    cp "$KEY_PATH" "${KEY_PATH}.bak.$(date +%Y%m%d-%H%M%S)"
fi

# 2) 生成 Ed25519 密钥对
echo "[2/5] 生成 Ed25519 密钥对"
node << 'NODEEOF'
const crypto = require('crypto');
const fs = require('fs');

const { publicKey, privateKey } = crypto.generateKeyPairSync('ed25519');

// 公钥 → JWK
const pubJwk = publicKey.export({ format: 'jwk' });
// 私钥 → PEM
const privPem = privateKey.export({ format: 'pem', type: 'pkcs8' });

const kid = 'axuan-callee-' + new Date().toISOString().slice(0, 10).replace(/-/g, '');
const agentId = 'axuan@172.28.0.5:3100';

const aid = {
  agent_id: agentId,
  kid: kid,
  alg: 'EdDSA',
  public_key: pubJwk,
  created_at: new Date().toISOString(),
  // 让 start-v5.sh slug 推导能找到（关键字段）
  slug: 'axuan',
  // 元数据
  display_name: '阿轩',
  version: '5.0.0',
  notes: 'Generated by 阿轩 via setup-handshake-axuan.sh on ' + new Date().toISOString()
};

fs.writeFileSync('csb-security/data/axuan-aid.json', JSON.stringify(aid, null, 2));
fs.writeFileSync('csb-security/data/axuan-private-key.pem', privPem);

console.log('  ✓ axuan-aid.json  kid=' + kid);
console.log('  ✓ axuan-private-key.pem  length=' + privPem.length);
NODEEOF

# 3) 验证文件
echo "[3/5] 验证生成结果："
ls -la csb-security/data/axuan-* 2>&1
echo "  --- AID 内容 ---"
cat csb-security/data/axuan-aid.json
echo "  --- 私钥前 80 字符 ---"
head -c 80 csb-security/data/axuan-private-key.pem
echo "..."

# 4) 设置权限（私钥 600）
echo "[4/5] 设置权限"
chmod 600 csb-security/data/axuan-private-key.pem
chmod 644 csb-security/data/axuan-aid.json

# 5) 提示下一步
echo ""
echo "[5/5] 完成。下一步："
echo "  1) 修 /home/node/.openclaw/workspace/start-v5.sh 把 Jeason 改成 axuan"
echo "  2) 启动 v5 (前台看输出):"
echo "     cd /home/node/.openclaw/workspace/csb-a2a-aip"
echo "     set -a && . ./.env && set +a"
echo "     node server_v5.js"
echo "  3) 验证握手:"
echo "     curl http://127.0.0.1:3100/a2a/handshake/status"
echo "  4) 把 csb-security/data/axuan-aid.json 发给若兰（公开信息）"
